services:
  - type: web
    name: whatsappwebclone-ctfp
    env: node
    buildCommand: npm run build
    startCommand: npm start
    staticPublishPath: client/build
    envVars:
      - key: MONGODB_URI
        sync: false
